{% set name = "redis-dict" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redis_dict-{{ version }}.tar.gz
  sha256: 7567e4f04eeb1d270001760c65174b55a03536e30e119f3f2bdf2d25b44da341

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - redis-py

test:
  imports:
    - redis_dict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Attumm/redis-dict
  summary: Dictionary with Redis as storage backend
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Attumm
    - mrakitin
