{% set name = "redis-dict" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redis_dict-{{ version }}.tar.gz
  sha256: a76e12597c27480e40a50477a46d25fddaff2352d32a4d02e7be415e63f25fa6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - redis-py

test:
  imports:
    - redis_dict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Attumm/redis-dict
  summary: Dictionary with Redis as storage backend
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Attumm
    - mrakitin
