{% set name = "redis-dict" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redis_dict-{{ version }}.tar.gz
  sha256: 6a249235db05871c6ff6b381c664b0c95c199c41d840234f54b3f9362070a745

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - redis-py

test:
  imports:
    - redis_dict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Attumm/redis-dict
  summary: Dictionary with Redis as storage backend
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Attumm
    - mrakitin
